name = "sportsball-live"
main = ".output/server/index.mjs"
compatibility_date = "2025-01-15"
compatibility_flags = ["nodejs_compat"]

[site]
bucket = ".output/public"

[vars]
VITE_SITE_URL = "https://sportsball.live"
